<a href="https://colab.research.google.com/github/Yasith-Banuka/PhyloMap/blob/master/Data/Save_Sequences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install biopython

In [1]:
import os
from Bio import SeqIO
from Bio import Entrez
import Bio
import pandas as pd

In [2]:
covid_df = pd.read_csv(
    "/content/drive/MyDrive/BioS_Project/Data/covid_all.csv"
)

dengue_df = pd.read_csv(
    "/content/drive/MyDrive/BioS_Project/Data/dengue_all.csv"
)

ebola_df = pd.read_csv(
    "/content/drive/MyDrive/BioS_Project/Data/ebola_all.csv"
)

enterovirus_df = pd.read_csv(
    "/content/drive/MyDrive/BioS_Project/Data/enterovirus_all.csv"
)

measles_df = pd.read_csv(
    "/content/drive/MyDrive/BioS_Project/Data/measles_all.csv"
)

mumps_df = pd.read_csv(
    "/content/drive/MyDrive/BioS_Project/Data/mumps_all.csv"
)

tb_df = pd.read_csv(
    "/content/drive/MyDrive/BioS_Project/Data/tb_all.csv"
)

zika_df = pd.read_csv(
    "/content/drive/MyDrive/BioS_Project/Data/zika_all.csv"
)

dfList = [covid_df, dengue_df, ebola_df, enterovirus_df, measles_df, mumps_df, tb_df, zika_df]

viruses = ['covid', 'dengue', 'ebola', 'enterovirus', 'measles', 'mumps', 'tuberculosis', 'zika']

for id, df in enumerate(dfList):
  df.name = viruses[id]

In [3]:
covid_df.head()

                   strain  ... logistic_growth
0         Wuhan-Hu-1/2019  ...             NaN
1         Wuhan/WH01/2019  ...             NaN
2  CHN/P6-SARS-CoV-2/2020  ...             NaN
3           AUS/SA03/2020  ...             NaN
4           AUS/SA04/2020  ...             NaN

[5 rows x 20 columns]

In [ ]:
Entrez.email = "yoshani.ranaweera.17@cse.mrt.ac.lk"  

for df in dfList:

  !mkdir /content/drive/MyDrive/BioS_Project/Fasta_Files/{df.name}
  print("------------------------> ",df.name)
  accessionList = df['accession'].tolist()
  print(accessionList)

  for accession in accessionList:

    if accession == None:
      continue

    filename = "/content/drive/MyDrive/BioS_Project/Fasta_Files/"+df.name+"/"+accession+".fasta"
    if not os.path.isfile(filename):
        try:
          net_handle = Entrez.efetch(
              db="nucleotide", id=accession, rettype="fasta", retmode="text"
          )
          out_handle = open(filename, "w")
          out_handle.write(net_handle.read())
          out_handle.close()
          net_handle.close()
        except:
          print(accession, "not found in NCBI")